travis:
  secure:
    BINSTAR_TOKEN: 0nsO45x//ak1+g1ML7BPimh/lf3k7y92IrqhgBQsKF2C8ZNRWyFBEtj1IbbUFPj5ZaZuChM0LQyl4juSTJAPRSuG4s1XMXFglxe8l7ONGoMfPjrAKDK4EkXb3gtvey2fyulKU8lkmRhE+F19aJRtrDdsI5rz4bde7WNE3eE+OmKPUQqX9ykzdUsNqaGWE6AhDga2bhzSF74Va14ZGwDE2B/dStGCecQnq6AvsYJegvioPCNwbsfAnYjKY3+QDjX7X2GuxjR6xqF7VfRFBmV/WaoJdP3Btl1sSRpKKXFZVdyR8bdHR2OapyBpjj0XteHrQZDx5k4BcxTtrqXGhiLnqTzB1OvC3e+DuiC0Vmx4yL5lO8d/G57GrxGleS/sL60Tt3TRpF/w4Vzu367oYTsm1hbSBFCJHPy52/5UsbNSor+8wlC3uNlSKdLn2rpHQfeSKjhqGw62638i0nD573dnWftb7NYMOl6iboQPvl9w3OwTCzBLs4loBojVJjCYbKvIVAir2vl9j+VzIanUiUDPK13te6C1+ZjcJjOS9AFBB0P4OuqOdiUkzknVRjrd+x7RJFS/u6KNDC+HgbL44qZXr9BMRvmtaFXeUcyfPvwN8ECGMNZP7knIpFH00s3b14TN3HqUoJpwAsbRH0nTKJZiC0+YNx5DOcjeoGLc7gQ0lKo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
